default:
  image: docker:26.0.0
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $PUBLIC_REGISTRY_USER -p $PUBLIC_REGISTRY_PASSWORD $PUBLIC_REGISTRY_URL

stages:
  - build
  - deploy

build:
  stage: build
  script:
      - docker pull $CI_REGISTRY_IMAGE:latest || true
      - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:latest .
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  needs: [build]
  rules:
    - if: $CI_COMMIT_TAG
  script:
      - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      - docker image tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $PUBLIC_REGISTRY_IMAGE:$CI_COMMIT_TAG
      - docker image tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $PUBLIC_REGISTRY_IMAGE:latest
      - docker push $PUBLIC_REGISTRY_IMAGE:$CI_COMMIT_TAG
      - docker push $PUBLIC_REGISTRY_IMAGE:latest
