default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $PUBLIC_REGISTRY_USER -p $PUBLIC_REGISTRY_PASSWORD $PUBLIC_REGISTRY_URL

stages:
  - build

build:
  stage: build
  script:
      - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $CI_REGISTRY_IMAGE:latest -t $PUBLIC_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG -t $PUBLIC_REGISTRY_IMAGE:latest .
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      - docker push $CI_REGISTRY_IMAGE:latest
      - docker push $PUBLIC_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      - docker push $PUBLIC_REGISTRY_IMAGE:latest
