{
  'log_level': 20, # 10 = DEBUG, CRITICAL = 50,FATAL = CRITICAL, ERROR = 40, WARNING = 30, WARN = WARNING, INFO = 20, DEBUG = 10, NOTSET = 0
  'nfvcl': {
    'port': 5002,
    'ip': ''
  },
  'osm': {
    'host': '127.0.0.1',
    'port': '9999',
    'username':'admin',
    'password':'admin',
    'project': 'admin',
    'version': 12
  },
  'mongodb': {
    'host': '127.0.0.1',
    'port': 27017,
    'db': 'nfvcl'
  },
  'prometheus': [{
    'scrap_file': '/etc/prometheus/nfvcl.yaml',
    'host': '127.0.0.1',
    'port': 22,
    'user': 'root',
    'passwd': 'password'
  }],
  'redis': {
    'host': '127.0.0.1',
    'port': 6379
  },
  'blue_types': {
    # "Amari5G": {"class_name": "Amari5G", "module_name": "blue_amari5G"},
    "Free5GC_K8s": {"class_name": "Free5GC_K8s", "module_name": "blue_free5gc"},
    "K8s": {"class_name": "K8s", "module_name": "blue_k8s"},
    "K8sBeta": {"class_name": "K8sBeta", "module_name": "blue_k8s"},
    "VO": {"class_name": "VO", "module_name": "blue_vo"},
    "UeRanSim": {"class_name": "UeRanSim", "module_name": "blue_ueransim"},
    "mqtt": {"class_name": "MqttBroker", "module_name": "blue_mqtt"},
    "Trex": {"class_name": "Trex", "module_name": "blue_trex"},
    "VyOSBlue": {"class_name": "VyOSBlue", "module_name": "blue_vyos"},
    "BlueSDCore": {"class_name": "BlueSDCore", "module_name": "blue_sdcore"},
    "OpenAirInterface_K8s": {"class_name": "OpenAirInterface_K8s", "module_name": "blue_oai_cn5g"}
  }
}
