[tool.poetry]
name = "nfvcl"
version = "0.2.2"
description = ""
authors = ["TNT LAB <staff@tnt-lab.unige.it>"]
maintainers = [
    "Paolo Bono <paolob@tnt-lab.unige.it>",
    "Alderico Gallo <aldericog@tnt-lab.unige.it>",
    "Davide Freggiaro <davidef@tnt-lab.unige.it>",
]
license = "n\b"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.2"
"ruamel.yaml" = "^0.18.6"
"jinja2-ansible-filters" = "^1.3.2"
redis = "^5.0.1"
"ruamel.yaml.jinja2" = "^0.2.7"
kubernetes = "28.1.0"
uvicorn = "^0.27.1"
pydantic = "^2.6.1"
pyOpenSSL = "24.0.0"
pymongo = "^4.6.1"
paramiko = "^3.4.0"
requests = "^2.32.0"
python-neutronclient = "^11.1.0"
openstacksdk = "^3.0.0"
coloredlogs = "^15.0.1"
colorama = "^0.4.6"
verboselogs = "^1.7"
ansible-runner = "^2.3.5"
ansible = "^9.2.0"
pyhelm3 = "^0.2.0"
httpx = {extras = ["http2"], version = "^0.26.0"}
jinja2 = "^3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
