[tool.poetry]
name = "nfvcl"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "n\b"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103.2"
"ruamel.yaml" = "^0.17.35"
"jinja2-ansible-filters" = "^1.3.2"
redis = "^5.0.1"
"ruamel.yaml.jinja2" = "^0.2.7"
kubernetes = "26.1.0"
uvicorn = "^0.23.2"
pydantic = "^2.4.2"
pyOpenSSL = "23.1.1"
pymongo = "^4.5.0"
paramiko = "^3.3.1"
requests = "^2.31.0"
python-neutronclient = "^11.0.0"
coloredlogs = "^15.0.1"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
