---
- hosts: all
  tasks:
  - name: Disable unattended-upgrades
    shell: |
      systemctl stop unattended-upgrades
      apt-get purge unattended-upgrades -y
  - name: Install screen
    apt:
      name:
        - screen
...
