apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisService.name }}
  namespace: {{ .Values.namespace }}-{{ .Release.Name }}
  labels:
    {{- include "helm-nfvcl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redisService.type }}
  ports:
    - port: {{ .Values.redisService.port }}
      targetPort:  {{ .Values.redisService.targetPort }}
      nodePort: {{ .Values.redisService.nodePort }}
      protocol: TCP
      name: redis-port
  selector:
    {{- include "helm-nfvcl.selectorLabels" . | nindent 4 }}
    {{- with .Values.redisPodLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
