---
- hosts: all
  gather_facts: no

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_network_os: vyos
    - ansible_connection: network_cli

  tasks:
  - name: description of eth0
    vyos.vyos.vyos_config:
      lines:
      - set interface ethernet eth0 description 'Management Network'
      save: yes
...