apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-mongodata
    namespace: {{ .Values.namespace }}
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: openebs-hostpath
    resources:
        requests:
            storage: 10Gi
