apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-mongodata
    namespace: {{ .Values.namespace }}-{{ .Release.Name }}
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: openebs-hostpath
    resources:
        requests:
            storage: 10Gi
