---
log_level: "20"
nfvcl:
  version: "0.3.0"
  port: "5002"
  ip: ""
mongodb:
  host: "127.0.0.1"
  port: "27017"
  db: "nfvcl"
  username: "admin"
  password: "password"
redis:
  host: "127.0.0.1"
  port: "6379"
