---
- hosts: all
  tasks:
  - name: Disable unattended-upgrades
    shell: |
      systemctl stop unattended-upgrades
      apt-get purge unattended-upgrades -y
  - name: Install screen and ethtool
    apt:
      name:
      - screen
      - ethtool
  - name: remove old gnb process
    shell: |
       ps ax | grep \.nb | grep SCREEN | awk '{ print $1}' | xargs kill
    ignore_errors: yes
  - name: Disable NIC offloading
    when: {{ confvar.disable_offloading | length > 0 }}
    shell: |
      ethtool --offload {{ confvar.disable_offloading }} rx off tx off
  - name: Add IP route
    when: {{ confvar.additional_ip_route | length > 0 }}
    shell: |
      ip r add {{ confvar.additional_ip_route }}
  - name: starting gnb
    shell: |
        screen -S nb -d -m bash -c '/root/UERANSIM/build/nr-gnb -c {{ confvar.conf_file }}'
        sleep 1
...
