---
- hosts: workers
  gather_facts: no
  tasks:
   - name: Download the certificate of the testbed docker registry
     shell: openssl s_client -showcerts -cipher DEFAULT@SECLEVEL=1 -connect docker-registry.maas:5000 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /usr/local/share/ca-certificates/ca.crt
   - name: Add the certificate of the testbed docker registry
     shell: update-ca-certificates
   - name: Join the Worker nodes with master.
     command: "{{ master_key }}"
     register: joined_or_not
   - debug:
       msg: "{{ joined_or_not.stdout }}"
...
