---

- hosts: all
  become: yes
  ##gather_facts: no
  # the first part never run since using addplaybook function only tasks are important
  #vars:
  # these vars are going to add by the addplaybook function
#  vars:
#    - int4: 'ens4' 10
#    - int5: 'ens5' 11
#    - ip1: 192.168.1.10 ->net1_int_ip
#    - gw1: 192.168.1.255 => net1_gw
#    - ip2: 192.168.2.10 => net2_int_ip
#    - gw2: 192.168.2.255 => net2_gw
#    - cap2_name: "http_simples" #{{ cap2_name }}

  tasks:
    - name: update repisotory
      apt:
        update_cache: yes
        upgrade: yes
    # pre-requirements for debian
    #- name: install kernel headers on debian based systems
     # apt:
        # for specify kernel we use {{ }}
      #  name: linux-header-{{ ansible_kernel }}
       # state: present
        #update_cache: yes

    - name: install build-essential
      apt:
        name: build-essential
        state: present

    - name: install python3-distutils
      apt:
        name: python3-distutils
        state: present
        update_cache: yes

    # I think doesn't need
    # no it must be presented otherwise we will have error
    - name: create trex folder
      file:
        path: /opt/trex-v2.92
        state: directory

    - name: install unzip
      package:
        name: unzip

    - name: install trex on local machine
      unarchive:
        src: http://192.168.17.60/ftp/upload/trex/v2.92.tar.gz
        dest: /opt/trex-v2.92
        remote_src: yes
        mode: 0755
        owner: root
        group: root

# Modify and create config files from input
#   Note: we can use block to copy all the lines to a new file !, here I chose to modify a created file
# Step1: create trex.cfg file from trex_07_cfg.yaml and copy to /etc/trex_cfg.yaml
# step2: create cap2 file from input (for http_simple) from the samples in /opt/cap2 and modify regarding the ip add and other parameters
# step3: set temporarily IP address for the extra-nets to run (Do we need fixed IP !!!)

# start step1:
    - name: copy trex_07_cfg.yaml to /etc/trex_cfg.yaml
      shell: cp /opt/trex-v2.92/v2.92/cfg/trex_07_cfg.yaml /etc/trex_cfg.yaml

    - name: remove port limit
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: '- port_limit:'
        state: absent

# im not sure if this is required, to be in safe side I did it
    - name: modify cfg file
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: 'version'
        line: "- version: 2"
        state: present

# This line need to modify regarding the name of ints
    - name: modify cfg file
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: 'interfaces:'
        line: "  interfaces: ['{{ int4 }}', '{{ int5 }}']"
        state: present

    - name: remove ip1,2
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: '- ip:'
        state: absent

    - name: remove gw1,2
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: 'default_gw'
        state: absent

    - name: add  ip1 line
      lineinfile:
        path: /etc/trex_cfg.yaml
        #no need regexp because it first apply and does not apply insertafter
        # regexp: 'port_info:'
        insertafter: 'port_info:'
        line: "      - ip: {{ net1_int_ip }}"
        state: present

    - name: add  gw1 line
      lineinfile:
        path: /etc/trex_cfg.yaml
        #regexp: 'port_info:'
        insertafter: 'ip:'
        line: "        default_gw: {{ net1_gw }}"

    - name: add  ip2 line
      lineinfile:
        path: /etc/trex_cfg.yaml
        #regexp: 'port_info:'
        insertafter: 'default_gw:'
        line: "      - ip: {{ net2_int_ip }}"

    - name: add  gw2 line
      lineinfile:
        path: /etc/trex_cfg.yaml
        #regexp: 'port_info:'
        insertafter: 'ip'
        line: "        default_gw: {{ net2_gw }}"

    - name: remove memory conditions
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: '        dp_flows    :'
        state: absent

    - name: remove memory
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: '  memory    : '
        state: absent

    - name: set socket equal to 0
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: '- socket:'
        line: '        - socket: 0'
        state: present


    - name: modify threads
      lineinfile:
        path: /etc/trex_cfg.yaml
        regexp: 'threads:'
        line: "          threads: [2,3]"
        # There is a doubt here!! >>> since using two threads meaning number of CPU must be twice !!

# start step2: creating required cap file
# regarding the input only adding the reference file in this part is enough the rest configuration is done automatically
    - name: copy http_cap file to /etc/cap_customized.yaml
      shell: cp /opt/trex-v2.92/v2.92/cap2/http_simple.yaml /etc/cap_customized.yaml
      when: cap2_name|string == "http"

    - name: copy sfr_cap file to /etc/cap_customized.yaml
      shell: cp /opt/trex-v2.92/v2.92/cap2/sfr.yaml /etc/cap_customized.yaml
      when: cap2_name|string == "sfr"

    - name: copy tcp_cap file to /etc/cap_customized.yaml
      shell: cp /opt/trex-v2.92/v2.92/cap2/short_tcp.yaml /etc/cap_customized.yaml
      when: cap2_name|string == "tcp"

    - name: copy sip_cap file to /etc/cap_customized.yaml
      shell: cp /opt/trex-v2.92/v2.92/cap2/sip_short1.yaml /etc/cap_customized.yaml
      when: cap2_name|string == "sip"

# using with_item to do all together
    - name: creating and modifyin cap_customized.yaml file
      lineinfile:
        path: "{{ item.dest }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - {dest: '/etc/cap_customized.yaml', regexp: "clients_start", line: "          clients_start : {{ net1_int_ip }}"}
        - {dest: '/etc/cap_customized.yaml', regexp: "clients_end", line: "          clients_end : {{ net1_int_ip }}"}
        - {dest: '/etc/cap_customized.yaml', regexp: "servers_start", line: "          servers_start : {{ net2_int_ip }}"}
        - {dest: '/etc/cap_customized.yaml', regexp: "servers_end", line: "          servers_end : {{ net2_int_ip }}"}
        - {dest: '/etc/cap_customized.yaml', regexp: "clients_per_gb", line: "          clients_per_gb : 10"}
        - {dest: '/etc/cap_customized.yaml', regexp: "min_clients", line: "          min_clients : 101"}
#        - {dest: '/etc/cap_customized.yaml', regexp: "cps", line: "       cps : 1.1"}
#        - {dest: '/etc/cap_customized.yaml', regexp: "ipg", line: "       ipg : 1000"}
#        - {dest: '/etc/cap_customized.yaml', regexp: "rtt", line: "       rtt : 1000"}

# make it more general, configured all cap files with small values of cps, ipg and rtt
    - name: modify caps, ipg, rtt values in cap_customized.yaml
      replace:
        path: "{{ item.dest }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - {dest: '/etc/cap_customized.yaml', regexp: '(cps : \d*.\d*)', replace: "cps : 1.1"} # this regexp used group but is the same
        - {dest: '/etc/cap_customized.yaml', regexp: 'ipg : \d*.\d*', replace: "ipg : 1000"}
        - {dest: '/etc/cap_customized.yaml', regexp: 'rtt : \d*.\d*', replace: "rtt : 1000"}

    # Set not permanent ip address
    - name: Set temporary Net1 Ip address
      shell: ifconfig ens4 10.0.10.195 netmask 255.255.255.0
      args:
#        chdir:  /opt/trex-{{ trex_version }}/{{ trex_version }}
        chdir:  /opt/trex-v2.92/v2.92

    - name: Set temporary Net2 Ip address
      shell: ifconfig ens5 10.0.11.35 netmask 255.255.255.0

    # added vars from ansible_vars (run_duration, cap2_name) list of dictionaries.
    - name: run trex scritps
#      shell: nohup ./t-rex-64  --cfg /etc/trex_cfg.yaml -f cap2/cap_customized.yaml -d {{ run_duration }} –m 1 –c 1 –k 5 --nc > first_run_logs.txt
      shell: ./t-rex-64  --cfg /etc/trex_cfg.yaml -f /etc/cap_customized.yaml -d {{ run_duration }} –m 1 –c 1 –k 5 --nc > first_run_logs.txt
      args:
        chdir: /opt/trex-v2.92/v2.92

    # this works but now removed to check the vars
#    - name: run trex scritps
#      shell: nohup ./t-rex-64  --cfg /etc/trex_cfg.yaml -f cap2/http_simple_mirej.yaml -d 10 –m 1 –c 1 –k 5 --nc > first_run_logs.txt
#      args:
##        chdir:  /opt/trex-{{ trex_version }}/{{ trex_version }}

    - name: get trex results file
      shell: cat /opt/trex-v2.92/v2.92/first_run_logs.txt
      register: trex_results_file
#
    - name: return trex results
      debug:
        msg: "{{ trex_results_file }}"
