{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helmflexvnfm.serviceAccountName" . }}
  labels:
{{ include "helmflexvnfm.labels" . | indent 4 }}
{{- end -}}
