apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helmflexvnfm.fullname" . }}
  labels:
{{ include "helmflexvnfm.labels" . | indent 4 }}
spec:
  serviceName:  {{ include "helmflexvnfm.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helmflexvnfm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helmflexvnfm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        vnf: {{ .Values.global.osm.vnf_id | lower}}
    spec:
      imagePullSecrets:
      - name: regcred 
      serviceAccountName: {{ template "helmflexvnfm.serviceAccountName" . }}
      securityContext:
        runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: osm-ee
            mountPath: /app/storage
          securityContext:
            allowPrivilegeEscalation: true
      volumes:      
      - name: osm-ee
        hostPath:
          path: /var/lib/osm/osm/osm_osm_packages/_data
