---
- hosts: all
  tasks:
  - name: add k8s hosts to hosts file
    shell: |
       echo "" >> /etc/hosts
       {% for elem in confvar.hosts %}
       echo "{{ elem.name }} {{ elem.ip }}" >> /etc/hosts
       {% endfor %}
  - name: starting process in a screen shell
    shell: |
       screen -S {{ confvar.type }} -d -m bash -c '/root/free5gc/bin/{{ confvar.type }} --{{ confvar.type }}cfg /root/free5gc/config/{{ confvar.type }}cfg.yaml'
       sleep 1
...
